spring:
  datasource:
    username: traum
    password: 621248ld
    url: jdbc:mysql://172.16.0.6:3306/traum?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 30000

server:
  port: 8080
  servlet:
    context-path: /dt
mybatis:
  mapper-locations: classpath:mapping/*/*Mapper.xml
  type-aliases-package: com.d.main.*.model
